import { integer, real, sqliteTable, text } from 'drizzle-orm/sqlite-core';

// Items/Products
export const items = sqliteTable('items', {
    id: text('id').primaryKey(),
    organizationId: text('organizationId').notNull(),
    branchId: text('branchId'),
    name: text('name').notNull(),
    nameLowercase: text('nameLowercase').notNull(),
    price: real('price').notNull(),
    purchasePrice: real('purchasePrice').default(0),
    mrp: real('mrp').default(0),
    hsn: text('hsn'),
    gstPercentage: real('gstPercentage').default(0),
    stock: integer('stock').default(0),
    minimumStock: integer('minimumStock').default(0),
    openingStock: integer('openingStock').default(0),
    unit: text('unit').default('pcs'),
    category: text('category'),
    subcategory: text('subcategory'),
    description: text('description'),
    location: text('location'),
    image: text('imageUrl'),
    barcode: text('barcode'),
    expiresAt: text('expiresAt'),
    autoDeleteAt: text('autoDeleteAt'),
    autoDeleteEnabled: integer('autoDeleteEnabled', { mode: 'boolean' }).default(false),
    isActive: integer('isActive', { mode: 'boolean' }).default(true),
    updatedAt: text('updatedAt'),
    createdAt: text('createdAt'),
});

// Parties (customers/suppliers)
export const parties = sqliteTable('parties', {
    id: text('id').primaryKey(),
    organizationId: text('organizationId'),
    name: text('name').notNull(),
    nameLowercase: text('nameLowercase').notNull(),
    type: text('type').notNull(),
    phone: text('phone'),
    email: text('email'),
    address: text('address'),
    gstNumber: text('gstNumber'),
    isActive: integer('isActive', { mode: 'boolean' }).default(true),
    updatedAt: text('updatedAt'),
    createdAt: text('createdAt'),
});

// Transactions (invoices/bills)
export const transactions = sqliteTable('transactions', {
    id: text('id').primaryKey(),
    organizationId: text('organizationId'),
    branchId: text('branchId'),
    accountId: text('accountId'),
    type: text('type').notNull(),
    partyId: text('partyId'),
    partyName: text('partyName'),
    partyPhone: text('partyPhone'),
    billNumber: text('billNumber'),
    billDate: text('billDate').notNull(),
    businessName: text('businessName'),
    businessAddress: text('businessAddress'),
    gstNumber: text('gstNumber'),
    currency: text('currency').default('INR'),
    costCenter: text('costCenter'),
    projectCode: text('projectCode'),
    totalAmount: real('totalAmount').notNull(),
    discountAmount: real('discountAmount').default(0),
    taxAmount: real('taxAmount').default(0),
    paidAmount: real('paidAmount').default(0),
    paymentMode: text('paymentMode').default('CASH'),
    paymentStatus: text('paymentStatus').default('PAID'),
    billMode: text('billMode').default('ESTIMATE'),
    affectsGst: integer('affectsGst', { mode: 'boolean' }).default(true),
    createdByUid: text('createdByUid'),
    dueDate: text('dueDate'),
    reminderEnabled: integer('reminderEnabled', { mode: 'boolean' }).default(false),
    reminderFrequencyDays: integer('reminderFrequencyDays').default(3),
    nextReminderAt: text('nextReminderAt'),
    lastReminderAt: text('lastReminderAt'),
    remark: text('remark'),
    billingAddress: text('billingAddress'),
    deliveryAddress: text('deliveryAddress'),
    deliveryContactName: text('deliveryContactName'),
    deliveryContactPhone: text('deliveryContactPhone'),
    itemsSnapshot: text('itemsSnapshot'),
    createdAt: text('createdAt'),
    updatedAt: text('updatedAt'),
});

// Cash/Bank accounts
export const accounts = sqliteTable('accounts', {
    id: text('id').primaryKey(),
    organizationId: text('organizationId').notNull(),
    name: text('name').notNull(),
    type: text('type').notNull(),
    balance: real('balance').default(0),
    isDefault: integer('isDefault', { mode: 'boolean' }).default(false),
    isActive: integer('isActive', { mode: 'boolean' }).default(true),
    isSystem: integer('isSystem', { mode: 'boolean' }).default(false),
    details: text('details'),
    createdAt: text('createdAt').notNull(),
    updatedAt: text('updatedAt').notNull(),
});
