import type { AppLanguage } from './appPreferences';

type CopyDictionary = Record<string, string>;

const en: CopyDictionary = {
    'tab.dashboard': 'Dashboard',
    'tab.settings': 'Settings',
    'tab.quick_actions': 'Quick Actions',
    'tab.quick_actions_eyebrow': 'Create and move',
    'tab.quick_actions_subtitle': 'Start the most-used billing and accounting flows from anywhere.',
    'tab.close': 'Close',
    'drawer.workspace': 'Workspace',
    'drawer.navigate_faster': 'Navigate faster',
    'drawer.active_business': 'Active business',
    'drawer.shortcuts': '{count} shortcuts',
    'drawer.search_placeholder': 'Search drawer actions...',
    'drawer.open_workflow': 'Open workflow',
    'settings.title': 'Settings',
    'settings.subtitle': 'All preferences in one place',
    'settings.hub_title': 'Settings Hub',
    'settings.hub_subtitle': 'Business configuration, app preferences, printing, taxes, inventory, and security.',
    'settings.search_placeholder': 'Search any setting...',
    'settings.no_results': 'No results',
    'settings.no_results_subtitle': 'Try a different setting name or section.',
    'settings.no_settings': 'No settings here',
    'settings.no_settings_subtitle': 'This category has no configurable options.',
    'settings.appearance_group': 'Appearance',
    'settings.documents_group': 'Documents',
    'settings.interaction_group': 'Interaction',
    'settings.security_group': 'Security',
    'settings.theme_mode': 'Theme Mode',
    'settings.language': 'Language',
    'settings.language_sub': 'Switch app labels and document copy.',
    'settings.invoice_template': 'Invoice Template',
    'settings.invoice_template_sub': 'Choose the default invoice look for preview, share, and print.',
    'settings.rich_motion': 'Rich Motion',
    'settings.rich_motion_sub': 'Use smoother transitions and card emphasis where available.',
    'settings.haptics': 'Haptics',
    'settings.haptics_sub': 'Tactile feedback on taps, tabs, and key actions.',
    'settings.gesture_navigation': 'Gesture Navigation',
    'settings.gesture_navigation_sub': 'Allow drawer swipe and gesture-friendly movement controls.',
    'settings.biometric_lock': 'Biometric App Lock',
    'settings.biometric_lock_sub': 'Require fingerprint or face unlock when returning to the app.',
    'settings.local_note': 'Theme, language, motion, gesture, and biometric preferences stay on this device.',
    'theme.system': 'System',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'lock.title': 'Unlock Vahi',
    'lock.subtitle': 'Biometric lock is enabled for this device.',
    'lock.unlock': 'Unlock',
    'lock.retry': 'Try again',
    'lock.unavailable': 'Biometric authentication is not available on this device.',
    'language.en': 'English',
    'language.hi': 'Hindi',
    'invoice_template.business': 'Business',
    'invoice_template.branded': 'Branded',
    'invoice.label.invoice': 'Invoice',
    'invoice.label.invoice_no': 'Invoice No',
    'invoice.label.date': 'Date',
    'invoice.label.party': 'Party',
    'invoice.label.description': 'Description',
    'invoice.label.qty': 'Qty',
    'invoice.label.rate': 'Rate',
    'invoice.label.amount': 'Amount',
    'invoice.label.total_qty': 'Total Qty',
    'invoice.label.invoice_total': 'Invoice Total',
    'invoice.label.received': 'Received',
    'invoice.label.balance': 'Balance',
    'invoice.label.status': 'Status',
    'invoice.label.notes': 'Notes',
    'invoice.label.terms': 'Terms & Conditions',
    'invoice.label.authorized_signatory': 'Authorized Signatory',
    'invoice.label.due': 'Due',
    'invoice.label.upi': 'UPI',
    'invoice.label.page': 'Page 1',
    'billing.not_found': 'Invoice not found.',
    'billing.status': 'Status',
    'billing.invoice_total': 'Invoice Total',
    'billing.gross_value': 'Gross value',
    'billing.balance_due': 'Balance Due',
    'billing.awaiting_settlement': 'Awaiting settlement',
    'billing.cleared': 'Cleared',
    'billing.bill_to': 'Bill To',
    'billing.phone': 'Phone',
    'billing.address': 'Address',
    'billing.items': 'Items',
    'billing.no_items': 'No items found',
    'billing.no_items_subtitle': 'This invoice has no visible line items.',
    'billing.totals': 'Totals',
    'billing.taxable_value': 'Taxable Value',
    'billing.discount': 'Discount',
    'billing.round_off': 'Round Off',
    'billing.paid_amount': 'Paid Amount',
    'billing.upi_qr': 'UPI Payment QR',
    'billing.pay_via_upi': 'Pay via UPI App',
    'billing.qr_not_required': 'Invoice is fully paid. QR not required.',
    'billing.qr_settings_hint': 'Set payment UPI ID in Settings > General to enable bill QR payment.',
    'billing.mark_as_paid': 'Mark as Paid',
    'billing.record_full_payment': 'Record full payment?',
    'billing.mark_paid': 'Mark Paid',
    'billing.print_pdf': 'Print / PDF',
    'billing.notes': 'Notes',
    'billing.no_upi_app_title': 'UPI',
    'billing.no_upi_app': 'No UPI app found on this device.',
    'billing.error_title': 'Error',
    'billing.error_pdf': 'Could not generate PDF',
};

const hi: CopyDictionary = {
    'tab.dashboard': 'डैशबोर्ड',
    'tab.settings': 'सेटिंग्स',
    'tab.quick_actions': 'क्विक एक्शन',
    'tab.quick_actions_eyebrow': 'बनाएं और चलाएं',
    'tab.quick_actions_subtitle': 'सबसे ज़्यादा उपयोग होने वाले बिलिंग और अकाउंटिंग काम यहीं से शुरू करें।',
    'tab.close': 'बंद करें',
    'drawer.workspace': 'वर्कस्पेस',
    'drawer.navigate_faster': 'तेज़ नेविगेशन',
    'drawer.active_business': 'सक्रिय बिजनेस',
    'drawer.shortcuts': '{count} शॉर्टकट',
    'drawer.search_placeholder': 'ड्रॉअर एक्शन खोजें...',
    'drawer.open_workflow': 'वर्कफ़्लो खोलें',
    'settings.title': 'सेटिंग्स',
    'settings.subtitle': 'सभी प्राथमिकताएं एक जगह',
    'settings.hub_title': 'सेटिंग्स हब',
    'settings.hub_subtitle': 'बिजनेस कॉन्फ़िगरेशन, ऐप प्राथमिकताएं, प्रिंटिंग, टैक्स, इन्वेंटरी और सुरक्षा।',
    'settings.search_placeholder': 'कोई भी सेटिंग खोजें...',
    'settings.no_results': 'कोई परिणाम नहीं',
    'settings.no_results_subtitle': 'दूसरा सेटिंग नाम या सेक्शन खोजें।',
    'settings.no_settings': 'यहां कोई सेटिंग नहीं',
    'settings.no_settings_subtitle': 'इस श्रेणी में कोई कॉन्फ़िगरेशन उपलब्ध नहीं है।',
    'settings.appearance_group': 'रूप',
    'settings.documents_group': 'दस्तावेज़',
    'settings.interaction_group': 'इंटरैक्शन',
    'settings.security_group': 'सुरक्षा',
    'settings.theme_mode': 'थीम मोड',
    'settings.language': 'भाषा',
    'settings.language_sub': 'ऐप लेबल और दस्तावेज़ कॉपी बदलें।',
    'settings.invoice_template': 'इनवॉइस टेम्पलेट',
    'settings.invoice_template_sub': 'प्रीव्यू, शेयर और प्रिंट के लिए डिफ़ॉल्ट इनवॉइस लुक चुनें।',
    'settings.rich_motion': 'रिच मोशन',
    'settings.rich_motion_sub': 'जहां उपलब्ध हो वहां स्मूद ट्रांज़िशन और कार्ड एंपहसिस इस्तेमाल करें।',
    'settings.haptics': 'हैप्टिक्स',
    'settings.haptics_sub': 'टैप, टैब और मुख्य एक्शन पर स्पर्श प्रतिक्रिया।',
    'settings.gesture_navigation': 'जेस्चर नेविगेशन',
    'settings.gesture_navigation_sub': 'ड्रॉअर स्वाइप और जेस्चर-फ्रेंडली कंट्रोल की अनुमति दें।',
    'settings.biometric_lock': 'बायोमेट्रिक ऐप लॉक',
    'settings.biometric_lock_sub': 'ऐप पर लौटने पर फिंगरप्रिंट या फेस अनलॉक आवश्यक करें।',
    'settings.local_note': 'थीम, भाषा, मोशन, जेस्चर और बायोमेट्रिक प्राथमिकताएं इसी डिवाइस पर रहती हैं।',
    'lock.title': 'वही अनलॉक करें',
    'lock.subtitle': 'इस डिवाइस पर बायोमेट्रिक लॉक सक्षम है।',
    'lock.unlock': 'अनलॉक',
    'lock.retry': 'फिर कोशिश करें',
    'lock.unavailable': 'इस डिवाइस पर बायोमेट्रिक प्रमाणीकरण उपलब्ध नहीं है।',
    'language.en': 'अंग्रेज़ी',
    'language.hi': 'हिंदी',
    'invoice_template.business': 'बिजनेस',
    'invoice_template.branded': 'ब्रांडेड',
    'invoice.label.invoice': 'इनवॉइस',
    'invoice.label.invoice_no': 'इनवॉइस नं',
    'invoice.label.date': 'तारीख',
    'invoice.label.party': 'पार्टी',
    'invoice.label.description': 'विवरण',
    'invoice.label.qty': 'मात्रा',
    'invoice.label.rate': 'रेट',
    'invoice.label.amount': 'राशि',
    'invoice.label.total_qty': 'कुल मात्रा',
    'invoice.label.invoice_total': 'कुल इनवॉइस',
    'invoice.label.received': 'प्राप्त',
    'invoice.label.balance': 'बकाया',
    'invoice.label.status': 'स्थिति',
    'invoice.label.notes': 'नोट्स',
    'invoice.label.terms': 'नियम और शर्तें',
    'invoice.label.authorized_signatory': 'अधिकृत हस्ताक्षरकर्ता',
    'invoice.label.due': 'बकाया',
    'invoice.label.upi': 'यूपीआई',
    'invoice.label.page': 'पृष्ठ 1',
};

export const APP_COPY: Record<AppLanguage, CopyDictionary> = {
    en,
    hi,
};

export const translateAppCopy = (
    language: AppLanguage,
    key: string,
    params?: Record<string, string | number>
): string => {
    const dictionary = APP_COPY[language] ?? APP_COPY.en;
    const template = dictionary[key] ?? APP_COPY.en[key] ?? key;
    if (!params) return template;
    return Object.entries(params).reduce(
        (result, [paramKey, value]) => result.replaceAll(`{${paramKey}}`, String(value)),
        template
    );
};
