
export const Colors = {
    light: {
        primary: '#1D4ED8',
        onPrimary: '#FFFFFF',
        primaryContainer: '#E8F0FF',
        onPrimaryContainer: '#0B2B78',
        secondary: '#0F5CC0',
        onSecondary: '#FFFFFF',
        secondaryContainer: '#E7F0FF',
        onSecondaryContainer: '#10356E',
        tertiary: '#0C4A6E',
        onTertiary: '#FFFFFF',
        tertiaryContainer: '#E0F2FE',
        onTertiaryContainer: '#0C3650',
        error: '#B42318',
        onError: '#FFFFFF',
        errorContainer: '#FEE4E2',
        onErrorContainer: '#5C1111',
        background: '#FFFFFF',
        onBackground: '#101828',
        surface: '#FFFFFF',
        onSurface: '#101828',
        surfaceVariant: '#F5F7FB',
        onSurfaceVariant: '#475467',
        outline: '#C7CED8',
        outlineVariant: '#E4E7EC',
        elevation: {
            level0: 'transparent',
            level1: '#FFFFFF',
            level2: '#FCFDFF',
            level3: '#FAFCFF',
            level4: '#F7FAFF',
            level5: '#F4F8FF',
        },
    },
    dark: {
        primary: '#22C55E',
        onPrimary: '#032410',
        primaryContainer: '#14532D',
        onPrimaryContainer: '#B7F7CF',
        secondary: '#16A34A',
        onSecondary: '#04210F',
        secondaryContainer: '#14532D',
        onSecondaryContainer: '#B7F7CF',
        tertiary: '#0EA5A4',
        onTertiary: '#032525',
        tertiaryContainer: '#115E59',
        onTertiaryContainer: '#A8F4ED',
        error: '#FDA29B',
        onError: '#661510',
        errorContainer: '#912018',
        onErrorContainer: '#FEE4E2',
        background: '#000000',
        onBackground: '#F5F5F5',
        surface: '#050505',
        onSurface: '#F5F5F5',
        surfaceVariant: '#111111',
        onSurfaceVariant: '#A3A3A3',
        outline: '#3A3A3A',
        outlineVariant: '#1F1F1F',
        elevation: {
            level0: 'transparent',
            level1: '#090909',
            level2: '#0D0D0D',
            level3: '#121212',
            level4: '#161616',
            level5: '#1A1A1A',
        },
    },
};
