
export const Colors = {
    light: {
        primary: '#0E7490',
        onPrimary: '#FFFFFF',
        primaryContainer: '#CFF3FA',
        onPrimaryContainer: '#083344',
        secondary: '#2563EB',
        onSecondary: '#FFFFFF',
        secondaryContainer: '#DBEAFE',
        onSecondaryContainer: '#1E3A8A',
        tertiary: '#EA580C',
        onTertiary: '#FFFFFF',
        tertiaryContainer: '#FFEDD5',
        onTertiaryContainer: '#7C2D12',
        error: '#B3261E',
        onError: '#FFFFFF',
        errorContainer: '#F9DEDC',
        onErrorContainer: '#410E0B',
        background: '#F4F7FB',
        onBackground: '#111827',
        surface: '#FFFFFF',
        onSurface: '#111827',
        surfaceVariant: '#E8EEF5',
        onSurfaceVariant: '#334155',
        outline: '#64748B',
        elevation: {
            level0: 'transparent',
            level1: '#F8FBFF',
            level2: '#F2F8FF',
            level3: '#ECF4FC',
            level4: '#E9F0F8',
            level5: '#E4ECF6',
        },
    },
    dark: {
        primary: '#67D4EA',
        onPrimary: '#0A3E4E',
        primaryContainer: '#0A4C60',
        onPrimaryContainer: '#CFF3FA',
        secondary: '#93C5FD',
        onSecondary: '#1E3A8A',
        secondaryContainer: '#1D4ED8',
        onSecondaryContainer: '#DBEAFE',
        tertiary: '#FDBA74',
        onTertiary: '#7C2D12',
        tertiaryContainer: '#9A3412',
        onTertiaryContainer: '#FFEDD5',
        error: '#F2B8B5',
        onError: '#601410',
        errorContainer: '#8C1D18',
        onErrorContainer: '#F9DEDC',
        background: '#0B1220',
        onBackground: '#E2E8F0',
        surface: '#111A2D',
        onSurface: '#E2E8F0',
        surfaceVariant: '#1D2940',
        onSurfaceVariant: '#BFCCD9',
        outline: '#93A8C0',
        elevation: {
            level0: 'transparent',
            level1: '#111F33',
            level2: '#15253B',
            level3: '#192B43',
            level4: '#1D304A',
            level5: '#213552',
        },
    },
};
