import type { InferSelectModel } from 'drizzle-orm';
import { plans } from '../db/schema';

export type PlanRow = InferSelectModel<typeof plans>;

export type PlanSeed = {
    id: string;
    tier: PlanRow['tier'];
    billingCycle: PlanRow['billingCycle'];
    displayName: string;
    description: string;
    pricePerCycle: number;
    currency: string;
    effectiveDiscountVsMonthlyPercent: number | null;
    displayOrder: number;
    maxBillsTotal: number | null;
    maxBillsPerMonth: number | null;
    maxStaffUsers: number | null;
    maxBusinesses: number | null;
    maxDevices: number | null;
    maxStorageMb: number | null;
    offlineOnly: boolean;
    cloudSyncAllowed: boolean;
    webDashboardAllowed: boolean;
    enabledFeatures: string[];
    disabledFeatures: string[];
    isVisible: boolean;
};

const ALL_FEATURES = [
    'OFFLINE_BILLING',
    'GST_INVOICES',
    'PURCHASE_MODULE',
    'STOCK_MODULE',
    'PARTY_MANAGEMENT',
    'GST_REPORTS',
    'ADVANCED_REPORTS',
    'E_INVOICE',
    'E_WAY_BILL',
    'MULTI_BUSINESS',
    'STAFF_USERS',
    'CLOUD_SYNC',
    'MULTI_DEVICE',
    'BACKUP_CLOUD',
    'EXPORT_PDF',
    'EXPORT_EXCEL',
    'ACCESS_WEB_DASHBOARD',
    'API_ACCESS',
    'BATCH_EXPIRY',
    'MULTI_GODOWN',
] as const;

const disabledFromAll = (enabled: string[]) => ALL_FEATURES.filter((flag) => !enabled.includes(flag));

export const DEFAULT_PLAN_SEEDS: PlanSeed[] = [
    {
        id: 'FREE_TRIAL',
        tier: 'FREE',
        billingCycle: null,
        displayName: 'Free Trial Plan',
        description: 'Trial of core billing and stock workflows in offline mode.',
        pricePerCycle: 0,
        currency: 'INR',
        effectiveDiscountVsMonthlyPercent: null,
        displayOrder: 1,
        maxBillsTotal: 50,
        maxBillsPerMonth: 50,
        maxStaffUsers: 0,
        maxBusinesses: 1,
        maxDevices: 1,
        maxStorageMb: 50,
        offlineOnly: true,
        cloudSyncAllowed: false,
        webDashboardAllowed: false,
        enabledFeatures: [
            'OFFLINE_BILLING',
            'GST_INVOICES',
            'PURCHASE_MODULE',
            'STOCK_MODULE',
            'PARTY_MANAGEMENT',
            'EXPORT_PDF',
        ],
        disabledFeatures: disabledFromAll([
            'OFFLINE_BILLING',
            'GST_INVOICES',
            'PURCHASE_MODULE',
            'STOCK_MODULE',
            'PARTY_MANAGEMENT',
            'EXPORT_PDF',
        ]),
        isVisible: true,
    },
    {
        id: 'STARTER_MONTHLY',
        tier: 'STARTER',
        billingCycle: 'MONTHLY',
        displayName: 'Starter Plan',
        description: 'Single business plan with cloud sync and GST basics.',
        pricePerCycle: 299,
        currency: 'INR',
        effectiveDiscountVsMonthlyPercent: null,
        displayOrder: 10,
        maxBillsTotal: null,
        maxBillsPerMonth: 2000,
        maxStaffUsers: 2,
        maxBusinesses: 1,
        maxDevices: 2,
        maxStorageMb: 2000,
        offlineOnly: false,
        cloudSyncAllowed: true,
        webDashboardAllowed: false,
        enabledFeatures: [
            'OFFLINE_BILLING',
            'GST_INVOICES',
            'PURCHASE_MODULE',
            'STOCK_MODULE',
            'PARTY_MANAGEMENT',
            'GST_REPORTS',
            'CLOUD_SYNC',
            'MULTI_DEVICE',
            'BACKUP_CLOUD',
            'EXPORT_PDF',
            'EXPORT_EXCEL',
        ],
        disabledFeatures: disabledFromAll([
            'OFFLINE_BILLING',
            'GST_INVOICES',
            'PURCHASE_MODULE',
            'STOCK_MODULE',
            'PARTY_MANAGEMENT',
            'GST_REPORTS',
            'CLOUD_SYNC',
            'MULTI_DEVICE',
            'BACKUP_CLOUD',
            'EXPORT_PDF',
            'EXPORT_EXCEL',
        ]),
        isVisible: true,
    },
    {
        id: 'STARTER_YEARLY',
        tier: 'STARTER',
        billingCycle: 'YEARLY',
        displayName: 'Starter Plan',
        description: 'Single business plan with cloud sync and GST basics.',
        pricePerCycle: 2999,
        currency: 'INR',
        effectiveDiscountVsMonthlyPercent: 16,
        displayOrder: 11,
        maxBillsTotal: null,
        maxBillsPerMonth: 2000,
        maxStaffUsers: 2,
        maxBusinesses: 1,
        maxDevices: 2,
        maxStorageMb: 2000,
        offlineOnly: false,
        cloudSyncAllowed: true,
        webDashboardAllowed: false,
        enabledFeatures: [
            'OFFLINE_BILLING',
            'GST_INVOICES',
            'PURCHASE_MODULE',
            'STOCK_MODULE',
            'PARTY_MANAGEMENT',
            'GST_REPORTS',
            'CLOUD_SYNC',
            'MULTI_DEVICE',
            'BACKUP_CLOUD',
            'EXPORT_PDF',
            'EXPORT_EXCEL',
        ],
        disabledFeatures: disabledFromAll([
            'OFFLINE_BILLING',
            'GST_INVOICES',
            'PURCHASE_MODULE',
            'STOCK_MODULE',
            'PARTY_MANAGEMENT',
            'GST_REPORTS',
            'CLOUD_SYNC',
            'MULTI_DEVICE',
            'BACKUP_CLOUD',
            'EXPORT_PDF',
            'EXPORT_EXCEL',
        ]),
        isVisible: true,
    },
    {
        id: 'GROWTH_MONTHLY',
        tier: 'GROWTH',
        billingCycle: 'MONTHLY',
        displayName: 'Growth Plan',
        description: 'For growing multi-branch businesses needing advanced GST workflows.',
        pricePerCycle: 699,
        currency: 'INR',
        effectiveDiscountVsMonthlyPercent: null,
        displayOrder: 20,
        maxBillsTotal: null,
        maxBillsPerMonth: 10000,
        maxStaffUsers: 10,
        maxBusinesses: 3,
        maxDevices: 5,
        maxStorageMb: 10000,
        offlineOnly: false,
        cloudSyncAllowed: true,
        webDashboardAllowed: true,
        enabledFeatures: [
            'OFFLINE_BILLING',
            'GST_INVOICES',
            'PURCHASE_MODULE',
            'STOCK_MODULE',
            'PARTY_MANAGEMENT',
            'GST_REPORTS',
            'ADVANCED_REPORTS',
            'E_INVOICE',
            'E_WAY_BILL',
            'MULTI_BUSINESS',
            'STAFF_USERS',
            'CLOUD_SYNC',
            'MULTI_DEVICE',
            'BACKUP_CLOUD',
            'EXPORT_PDF',
            'EXPORT_EXCEL',
            'ACCESS_WEB_DASHBOARD',
            'BATCH_EXPIRY',
            'MULTI_GODOWN',
        ],
        disabledFeatures: disabledFromAll([
            'OFFLINE_BILLING',
            'GST_INVOICES',
            'PURCHASE_MODULE',
            'STOCK_MODULE',
            'PARTY_MANAGEMENT',
            'GST_REPORTS',
            'ADVANCED_REPORTS',
            'E_INVOICE',
            'E_WAY_BILL',
            'MULTI_BUSINESS',
            'STAFF_USERS',
            'CLOUD_SYNC',
            'MULTI_DEVICE',
            'BACKUP_CLOUD',
            'EXPORT_PDF',
            'EXPORT_EXCEL',
            'ACCESS_WEB_DASHBOARD',
            'BATCH_EXPIRY',
            'MULTI_GODOWN',
        ]),
        isVisible: true,
    },
    {
        id: 'GROWTH_YEARLY',
        tier: 'GROWTH',
        billingCycle: 'YEARLY',
        displayName: 'Growth Plan',
        description: 'For growing multi-branch businesses needing advanced GST workflows.',
        pricePerCycle: 6999,
        currency: 'INR',
        effectiveDiscountVsMonthlyPercent: 16,
        displayOrder: 21,
        maxBillsTotal: null,
        maxBillsPerMonth: 10000,
        maxStaffUsers: 10,
        maxBusinesses: 3,
        maxDevices: 5,
        maxStorageMb: 10000,
        offlineOnly: false,
        cloudSyncAllowed: true,
        webDashboardAllowed: true,
        enabledFeatures: [
            'OFFLINE_BILLING',
            'GST_INVOICES',
            'PURCHASE_MODULE',
            'STOCK_MODULE',
            'PARTY_MANAGEMENT',
            'GST_REPORTS',
            'ADVANCED_REPORTS',
            'E_INVOICE',
            'E_WAY_BILL',
            'MULTI_BUSINESS',
            'STAFF_USERS',
            'CLOUD_SYNC',
            'MULTI_DEVICE',
            'BACKUP_CLOUD',
            'EXPORT_PDF',
            'EXPORT_EXCEL',
            'ACCESS_WEB_DASHBOARD',
            'BATCH_EXPIRY',
            'MULTI_GODOWN',
        ],
        disabledFeatures: disabledFromAll([
            'OFFLINE_BILLING',
            'GST_INVOICES',
            'PURCHASE_MODULE',
            'STOCK_MODULE',
            'PARTY_MANAGEMENT',
            'GST_REPORTS',
            'ADVANCED_REPORTS',
            'E_INVOICE',
            'E_WAY_BILL',
            'MULTI_BUSINESS',
            'STAFF_USERS',
            'CLOUD_SYNC',
            'MULTI_DEVICE',
            'BACKUP_CLOUD',
            'EXPORT_PDF',
            'EXPORT_EXCEL',
            'ACCESS_WEB_DASHBOARD',
            'BATCH_EXPIRY',
            'MULTI_GODOWN',
        ]),
        isVisible: true,
    },
    {
        id: 'GROWTH_THREE_YEAR',
        tier: 'GROWTH',
        billingCycle: 'THREE_YEAR',
        displayName: 'Growth Plan',
        description: 'For growing multi-branch businesses needing advanced GST workflows.',
        pricePerCycle: 17999,
        currency: 'INR',
        effectiveDiscountVsMonthlyPercent: 28,
        displayOrder: 22,
        maxBillsTotal: null,
        maxBillsPerMonth: 10000,
        maxStaffUsers: 10,
        maxBusinesses: 3,
        maxDevices: 5,
        maxStorageMb: 10000,
        offlineOnly: false,
        cloudSyncAllowed: true,
        webDashboardAllowed: true,
        enabledFeatures: [
            'OFFLINE_BILLING',
            'GST_INVOICES',
            'PURCHASE_MODULE',
            'STOCK_MODULE',
            'PARTY_MANAGEMENT',
            'GST_REPORTS',
            'ADVANCED_REPORTS',
            'E_INVOICE',
            'E_WAY_BILL',
            'MULTI_BUSINESS',
            'STAFF_USERS',
            'CLOUD_SYNC',
            'MULTI_DEVICE',
            'BACKUP_CLOUD',
            'EXPORT_PDF',
            'EXPORT_EXCEL',
            'ACCESS_WEB_DASHBOARD',
            'BATCH_EXPIRY',
            'MULTI_GODOWN',
        ],
        disabledFeatures: disabledFromAll([
            'OFFLINE_BILLING',
            'GST_INVOICES',
            'PURCHASE_MODULE',
            'STOCK_MODULE',
            'PARTY_MANAGEMENT',
            'GST_REPORTS',
            'ADVANCED_REPORTS',
            'E_INVOICE',
            'E_WAY_BILL',
            'MULTI_BUSINESS',
            'STAFF_USERS',
            'CLOUD_SYNC',
            'MULTI_DEVICE',
            'BACKUP_CLOUD',
            'EXPORT_PDF',
            'EXPORT_EXCEL',
            'ACCESS_WEB_DASHBOARD',
            'BATCH_EXPIRY',
            'MULTI_GODOWN',
        ]),
        isVisible: true,
    },
    {
        id: 'ENTERPRISE_YEARLY',
        tier: 'ENTERPRISE',
        billingCycle: 'YEARLY',
        displayName: 'Enterprise Plan',
        description: 'High-volume, multi-location workflows with API access.',
        pricePerCycle: 24999,
        currency: 'INR',
        effectiveDiscountVsMonthlyPercent: null,
        displayOrder: 30,
        maxBillsTotal: null,
        maxBillsPerMonth: null,
        maxStaffUsers: null,
        maxBusinesses: null,
        maxDevices: null,
        maxStorageMb: null,
        offlineOnly: false,
        cloudSyncAllowed: true,
        webDashboardAllowed: true,
        enabledFeatures: [...ALL_FEATURES],
        disabledFeatures: [],
        isVisible: true,
    },
    {
        id: 'ENTERPRISE_THREE_YEAR',
        tier: 'ENTERPRISE',
        billingCycle: 'THREE_YEAR',
        displayName: 'Enterprise Plan',
        description: 'High-volume, multi-location workflows with API access.',
        pricePerCycle: 64999,
        currency: 'INR',
        effectiveDiscountVsMonthlyPercent: 35,
        displayOrder: 31,
        maxBillsTotal: null,
        maxBillsPerMonth: null,
        maxStaffUsers: null,
        maxBusinesses: null,
        maxDevices: null,
        maxStorageMb: null,
        offlineOnly: false,
        cloudSyncAllowed: true,
        webDashboardAllowed: true,
        enabledFeatures: [...ALL_FEATURES],
        disabledFeatures: [],
        isVisible: true,
    },
];

export const FREE_PLAN_ID = 'FREE_TRIAL';
